### ISSUE TITLE
support for updated phpstan/phpstan

### ISSUE THREAD

**Issue by mzk** [thecodingmachine/phpstan-strict-rules#18]
```
composer require thecodingmachine/phpstan-strict-rules
- Conclusion: don't install thecodingmachine/phpstan-strict-rules v0.8.0|remove phpstan/phpstan 0.9.x-dev
    - Conclusion: don't install thecodingmachine/phpstan-strict-rules v0.8.0|don't install phpstan/phpstan 0.9.x-dev
    - Installation request for thecodingmachine/phpstan-strict-rules ^0.8.0@dev -> satisfiable by thecodingmachine/phpstan-strict-rules[0.8.x-dev, v0.8.0, v0.8.1, v0.8.2, v0.8.3, v0.8.4, v0.8.5].
    - thecodingmachine/phpstan-strict-rules v0.8.0 requires phpstan/phpstan ^0.8.0 -> satisfiable by phpstan/phpstan[0.8, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.x-dev].
```
The line `"phpstan/phpstan": "^0.8.0",` in `composer.json` is required?

**Comment by moufmouf** [comment]
Hey Olda,

Yes, the line is required. This is because thecodingmachine/phpstan-strict-rules has only been tested to work against phpstan 0.8 (which is the current "stable" branch).

phpstan 0.9 is the "dev" branch and not stable yet so I'm not developing phpstan-strict-rules against this branch yet (it may break at any point in time)
If PHPStan follows semantic versioning (I believe they do), that there can be "breaking changes" between 0.8 and 0.9.
When phpstan 0.9 is tagged, I will make sure thecodingmachine/phpstan-strict-rules is upgraded to be compatible with the new 0.9.
